#======服务器配置
server:
  port: 8080
spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/civbot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    hikari:
      minimum-idle: 5
      maximum-pool-size: 300
      max-lifetime: 1200000
  jackson:
    time-zone: GMT+8
minebot:
  account:
  password:
  admin:






